name: shop

services:
  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    ports:
      - '127.0.0.1:5432:5432/tcp'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.28-alpine-slim
    ports:
      - '127.0.0.1:1443:443/tcp'
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/cert:/cert:ro

  authelia:
    image: gchr.io/authelia/authelia:4.39
    ports:
      - '127.0.0.1:12001:9091/tcp'
    env_file:
      - identity/.env

# todo: inventory container
# todo: storefront container
# These containers should be qualified with [prod/qa] profiles.
# We would prefer to not run these services as containers during local development.
# Currently nginx proxies these routes to the host machine's network.

volumes:
  postgres-data:
