name: shop

services:
  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: postgres__user.shop.password # Replaced by setup script
      POSTGRES_DB: shop
    ports:
      - '127.0.0.1:5432:5432/tcp'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shop

  nginx:
    image: nginx:1.28-alpine-slim
    ports:
      - '127.0.0.1:1443:443/tcp'
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/authelia:/etc/nginx/authelia:ro
      - ./proxy/cert:/cert:ro
      - ./frontend/static:/frontend/static:ro
      - ./volatile:/volatile:ro
    restart: unless-stopped
    networks:
      - shop

  authelia-prod:
    profiles:
      - prod
    hostname: authelia
    image: authelia/authelia:4.39
    ports:
      - '127.0.0.1:11002:11002/tcp'
    environment:
      X_AUTHELIA_CONFIG: /config/configuration.prod.yaml
      X_AUTHELIA_CONFIG_FILTERS: template
    env_file:
      - path: ./identity/.env
        required: true
    volumes:
      - ./identity/config:/config
      - ./identity/secret:/secret
      - ./identity/data:/data
    restart: unless-stopped
    networks:
      - shop

  authelia-stage:
    profiles:
      - stage
    hostname: authelia
    image: authelia/authelia:4.39
    ports:
      - '127.0.0.1:11002:11002/tcp'
    environment:
      X_AUTHELIA_CONFIG: /config/configuration.stage.yaml
      X_AUTHELIA_CONFIG_FILTERS: template
    env_file:
      - path: ./identity/.env
        required: true
    volumes:
      - ./identity/config:/config
      - ./identity/secret:/secret
      - ./identity/data:/data
    restart: unless-stopped
    networks:
      - shop

  authelia-local:
    profiles:
      - local
    hostname: authelia
    image: authelia/authelia:4.39
    ports:
      - '127.0.0.1:11002:11002/tcp'
    environment:
      X_AUTHELIA_CONFIG: /config/configuration.local.yaml
      X_AUTHELIA_CONFIG_FILTERS: template
    env_file:
      - path: ./identity/.env
        required: true
    volumes:
      - ./identity/config:/config
      - ./identity/secret:/secret
      - ./identity/data:/data
    restart: unless-stopped
    networks:
      - shop

  authelia-validate:
    profiles:
      - validate
    image: authelia/authelia:4.39
    command: authelia config validate --config /config/configuration.yml
    env_file:
      - ./identity/.env
    volumes:
      - ./identity/config:/config
      - ./identity/secret:/secret
      - ./identity/data:/data
    restart: 'no'

# todo: inventory container
# todo: frontend container
# These containers should be qualified with [prod/qa] profiles.
# We would prefer to not run these services as containers during local development.
# Currently nginx proxies these routes to the host machine's network.

# todo: cloudflared container

volumes:
  postgres-data:

networks:
  shop:
    driver: bridge
