name: shop

x-nginx-common: &nginx_common
  image: nginx:1.28-alpine-slim
  ports:
    - '127.0.0.1:1443:443/tcp'
  restart: unless-stopped
  networks:
    - shop

x-authelia_common: &authelia_common
  hostname: authelia
  image: authelia/authelia:4.39
  ports:
    - '127.0.0.1:11002:11002/tcp'
  env_file:
    - path: ./identity/.env
      required: true
  volumes:
    - ./identity/config:/config
    - ./identity/secret:/secret
    - ./identity/data:/data
  restart: unless-stopped
  networks:
    - shop

x-application_common: &application_common
  env_file:
    - path: ./.env
      required: true
x-application_common_build: &application_common_build
  context: ./
  dockerfile: ./rust_package.containerfile
  network: shop

services:
  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: postgres__user.shop.password # Replaced by setup script
      POSTGRES_DB: shop
    ports:
      - '127.0.0.1:5432:5432/tcp'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shop

  nginx-local:
    <<: *nginx_common
    profiles:
      - local
    volumes:
      - ./proxy/nginx.local.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/authelia:/etc/nginx/authelia:ro
      - ./proxy/cert:/cert:ro
      - ./frontend/static:/frontend/static:ro
      - ./volatile:/volatile:ro

  nginx-stage:
    <<: *nginx_common
    profiles:
      - stage
    volumes:
      - ./proxy/nginx.stage.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/authelia:/etc/nginx/authelia:ro
      - ./proxy/cert:/cert:ro
      - ./frontend/static:/frontend/static:ro
      - ./volatile:/volatile:ro

  nginx-production:
    <<: *nginx_common
    profiles:
      - production
    volumes:
      - ./proxy/nginx.production.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/authelia:/etc/nginx/authelia:ro
      - ./proxy/cert:/cert:ro
      - ./frontend/static:/frontend/static:ro
      - ./volatile:/volatile:ro

  authelia-local:
    <<: *authelia_common
    profiles:
      - local
    environment:
      X_AUTHELIA_CONFIG: /config/configuration.local.yaml

  authelia-stage:
    <<: *authelia_common
    profiles:
      - stage
    environment:
      X_AUTHELIA_CONFIG: /config/configuration.stage.yaml

  authelia-production:
    <<: *authelia_common
    profiles:
      - production
    environment:
      X_AUTHELIA_CONFIG: /config/configuration.production.yaml

  authelia-validate:
    <<: *authelia_common
    profiles:
      - validate
    environment:
      X_AUTHELIA_CONFIG: /config/configuration.local.yaml
    command: authelia config validate
    restart: 'no'

  inventory-local:
    <<: *application_common
    profiles:
      - local
    build:
      <<: *application_common_build
      args:
        package_name_arg: inventory
        environment_arg: local
    ports:
      - "11001:11001"
    depends_on:
      - postgres
      - authelia-local
      - nginx-local

  inventory-stage:
    <<: *application_common
    profiles:
      - stage
    build:
      <<: *application_common_build
      args:
        package_name_arg: inventory
        environment_arg: stage
    ports:
      - "11001:11001"
    depends_on:
      - postgres
      - authelia-stage
      - nginx-stage

  inventory-production:
    <<: *application_common
    profiles:
      - production
    build:
      <<: *application_common_build
      args:
        package_name_arg: inventory
        environment_arg: production
    ports:
      - "11001:11001"
    depends_on:
      - postgres
      - authelia-production
      - nginx-production

  frontend-local:
    <<: *application_common
    profiles:
      - local
    build:
      <<: *application_common_build
      args:
        package_name_arg: frontend
        environment_arg: local
    ports:
      - "11000:11000"
    depends_on:
      - postgres
      - authelia-local
      - nginx-local

  frontend-stage:
    <<: *application_common
    profiles:
      - stage
    build:
      <<: *application_common_build
      args:
        package_name_arg: frontend
        environment_arg: stage
    ports:
      - "11000:11000"
    depends_on:
      - postgres
      - authelia-stage
      - nginx-stage

  frontend-production:
    <<: *application_common
    profiles:
      - production
    build:
      <<: *application_common_build
      args:
        package_name_arg: frontend
        environment_arg: production
    ports:
      - "11000:11000"
    depends_on:
      - postgres
      - authelia-production
      - nginx-production

# These containers should be qualified with [prod/qa] profiles.
# We would prefer to not run these services as containers during local development.
# Currently, nginx proxies these routes to the host machine's network.

# todo: cloudflared container

volumes:
  postgres-data:

networks:
  shop:
    driver: bridge
