name: shop

services:
  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    ports:
      - '127.0.0.1:5432:5432/tcp'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

