name: shop

x-nginx-common: &nginx_common
  image: nginx:1.28-alpine-slim
  ports:
    - '127.0.0.1:1443:443/tcp'
  restart: unless-stopped
  networks:
    - shop

x-authelia_common: &authelia_common
  hostname: authelia
  image: authelia/authelia:4.39
  ports:
    - '127.0.0.1:11002:11002/tcp'
  env_file:
    - path: ./identity/.env
      required: true
  volumes:
    - ./identity/config:/config
    - ./identity/secret:/secret
    - ./identity/data:/data
  restart: unless-stopped
  networks:
    - shop

x-rust_package_common: &rust_package_common
  env_file:
    - path: ./.env
      required: true
x-rust_package_common_build: &rust_package_common_build
  context: ./
  dockerfile: ./rust_package.containerfile
  network: shop

services:
  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: postgres__user.shop.password # Replaced by setup script
      POSTGRES_DB: shop
    ports:
      - '127.0.0.1:5432:5432/tcp'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shop

  nginx-local:
    <<: *nginx_common
    profiles:
      - local
    volumes:
      - ./proxy/nginx.local.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/authelia:/etc/nginx/authelia:ro
      - ./proxy/cert:/cert:ro
      - ./frontend/static:/frontend/static:ro
      - ./volatile:/volatile:ro

  nginx-stage:
    <<: *nginx_common
    profiles:
      - stage
    volumes:
      - ./proxy/nginx.stage.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/authelia:/etc/nginx/authelia:ro
      - ./proxy/cert:/cert:ro
      - ./frontend/static:/frontend/static:ro
      - ./volatile:/volatile:ro

  nginx-prod:
    <<: *nginx_common
    profiles:
      - prod
    volumes:
      - ./proxy/nginx.production.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/authelia:/etc/nginx/authelia:ro
      - ./proxy/cert:/cert:ro
      - ./frontend/static:/frontend/static:ro
      - ./volatile:/volatile:ro

  authelia-local:
    <<: *authelia_common
    profiles:
      - local
    environment:
      X_AUTHELIA_CONFIG: /config/configuration.local.yaml

  authelia-stage:
    <<: *authelia_common
    profiles:
      - stage
    environment:
      X_AUTHELIA_CONFIG: /config/configuration.stage.yaml

  authelia-prod:
    <<: *authelia_common
    profiles:
      - prod
    environment:
      X_AUTHELIA_CONFIG: /config/configuration.prod.yaml

  authelia-validate:
    <<: *authelia_common
    profiles:
      - validate
    environment:
      X_AUTHELIA_CONFIG: /config/configuration.local.yaml
    command: authelia config validate
    restart: 'no'
#
#  inventory:
#    <<: *rust_package_common
#    build:
#      <<: *rust_package_common_build
#      args:
#        package_name: inventory
#
#  frontend:
#    <<: *rust_package_common
#    build:
#      <<: *rust_package_common_build
#      args:
#        package_name: frontend

# todo: inventory container
# todo: frontend container
# These containers should be qualified with [prod/qa] profiles.
# We would prefer to not run these services as containers during local development.
# Currently nginx proxies these routes to the host machine's network.

# todo: cloudflared container

volumes:
  postgres-data:

networks:
  shop:
    driver: bridge
