[package]
name = "storefront"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { version = "0.4" }
env_logger = { version = "0.11.8" }
actix-web = { version = "4" }
maud = { version = "0.27", features = ["actix-web"] }
const_format = { version = "0.2.34", features = ["fmt"] }
