---
# yaml-language-server: $schema=https://www.authelia.com/schemas/v4.39/json-schema/configuration.json

###############################################################
#                   Authelia configuration                    #
###############################################################
# Within the Authelia container, this file is expected to reside at /config/configuration.yml

theme: dark

server:
  address: 'tcp://:11002/auth'
  endpoints:
    # https://www.authelia.com/configuration/miscellaneous/server-endpoints-authz/
    authz:
      auth-request:
        # https://www.authelia.com/integration/proxies/nginx/
        implementation: AuthRequest
        authn_strategies:
          - name: CookieSession
          - name: HeaderAuthorization
            schemes:
              - basic
            scheme_basic_cache_lifespan: 0

log:
  level: info
  format: text
  file_path: /data/~authelia.log
  keep_stdout: true

totp:
  #  issuer: zach.ro
  issuer: authelia

#identity_validation:
#  reset_password:
#    jwt_secret: 'defined via AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_FILE'

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the .env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: '/data/users_database.yml'

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: '*.zach.ro'
      policy: one_factor
    - domain: '*.authelia'
      policy: one_factor
    - domain: '127.0.0.1'
      policy: one_factor
#    - domain: 'public.example.com'
#      policy: 'bypass'
#    - domain: 'traefik.example.com'
#      policy: 'one_factor'
#    - domain: 'secure.example.com'
#      policy: 'two_factor'

session:
  # secret defined via AUTHELIA_SESSION_SECRET_FILE

  cookies:
    # https://www.authelia.com/integration/proxies/nginx/
    - name: 'authelia_session'
      domain: '127.0.0.1' # Should match whatever your root protected domain is
      # These links are used in 302 redirects, so they must be accessible from the public Internet
      authelia_url: 'https://127.0.0.1:1443/auth'
      default_redirection_url: 'https://127.0.0.1:1443/admin'
      expiration: '1 hour'
      inactivity: '5 minutes'

regulation:
  max_retries: 5
  find_time: '2 minutes'
  ban_time: '5 minutes'

storage:
  # encryption_key defined via AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
  postgres:
    address: 'tcp://postgres:5432' # This address is applicable only within the Docker Compose virtual network
    database: authelia
    schema: public
    username: authelia
    # password defined via AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
    # Do not connect with TLS

notifier:
  filesystem:
    filename: /data/notification.txt
#  smtp: # todo: set up email
#    username: 'test'
#    # This secret can also be set using the .env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
#    password: 'password'
#    address: 'smtp://mail.example.com:25'
#    sender: 'admin@example.com'

ntp:
  address: 'udp://time.cloudflare.com:123'
  max_desync: '3s'

...
